Repository flexycode/CTINFMGL_FINAL_PROJECT, pull requests merged in 2025-02, with the labels that each got.

#20 🚀 Entity Relationship Diagram
  assets/Front Page.png
  assets/Search Flight 2.png
  assets/Search Flight.png
  assets/Video Page.png
Labels: documentation, enhancement

#24 💾 Updated carts_table.sql
  database/carts_table.sql
Labels: documentation, enhancement, help wanted

#25 💾 Updated flight_names.sql
  database/flight_names.sql
Labels: documentation, enhancement, help wanted

#26 💾 Updated flights_table.sql
  database/flights_table.sql
Labels: documentation, enhancement, help wanted

#27 💾 Update seats_table.sql
  database/seats_table.sql
Labels: documentation, enhancement, help wanted

#29 👷 Backend Server-side
  backend/.gitignore
  backend/auth/adminAuth.js
  backend/auth/userAuth.js
  backend/config/emailConfig.js
  backend/config/mutlerConfig.js
  backend/controller/cartController.js
  backend/controller/chatbotController.js
  backend/controller/emailController.js
  backend/controller/flightController.js
  backend/controller/seatController.js
  backend/controller/userController.js
  backend/database/Mysql.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/cart.js
  backend/routes/chatbot.js
  backend/routes/email.js
  backend/routes/flights.js
  backend/routes/seat.js
  backend/routes/user.js
  backend/services/cartService.js
  backend/services/chatbotService.js
  backend/services/emailService.js
  backend/services/flightService.js
  backend/services/seatService.js
  backend/services/userService.js
  backend/views/index.ejs
Labels: enhancement, help wanted
